name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  enforce-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request title
        shell: bash
        env:
          PR_TITLE: "${{ github.event.pull_request.title }}"
        run: |
          if [[ "$PR_TITLE" =~ ^\[(MAJOR|MINOR|PATCH)\][[:space:]].+ ]]; then
            echo "PR title matches required format: $PR_TITLE"
          else
            echo "::error::Pull request title must match '[MAJOR|MINOR|PATCH] <description>'." >&2
            exit 1
          fi
